spring.application.name=spotify-scrobble
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0

spring.data.redis.host=localhost
spring.data.web.pageable.max-page-size=50


SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}

spring.jpa.show-sql=true

#Springboot oauth2 resource server
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_KEY_URI}

#Springboot oauth2 client
spring.security.oauth2.client.registration.spotifyscrobble.client-id=${SPOTIFY_CLIENT_ID}
spring.security.oauth2.client.registration.spotifyscrobble.client-secret=${SPOTIFY_CLIENT_SECRET}
spring.security.oauth2.client.registration.spotifyscrobble.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spotifyscrobble.scope=user-read-currently-playing,user-read-recently-played
spring.security.oauth2.client.registration.spotifyscrobble.redirect-uri=http://127.0.0.1:8080/callback
spring.security.oauth2.client.provider.spotifyscrobble.authorization-uri=https://accounts.spotify.com/authorize
spring.security.oauth2.client.provider.spotifyscrobble.token-uri=https://accounts.spotify.com/api/token